version: '3'
services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/api
      # If you add an volume here make sure you add it to /bin/download-infini-gram-array.sh too
      - ./infinigram-array/v4_pileval_llama:/mnt/infinigram-array/v4_pileval_llama
      - ./infinigram-array/dolma_1_7:/mnt/infinigram-array/dolma_1_7
      - ./infinigram-array/olmoe-mix-0924-dclm:/mnt/infinigram-array/olmoe-mix-0924-dclm
      - ./infinigram-array/olmoe-mix-0924-nodclm:/mnt/infinigram-array/olmoe-mix-0924-nodclm
      - ./infinigram-array/v4-ultrafeedback:/mnt/infinigram-array/v4-ultrafeedback
      - ./infinigram-array/v4-tulu-v3-1-mix:/mnt/infinigram-array/v4-tulu-v3-1-mix
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - INDEX_BASE_PATH=/mnt/infinigram-array
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
  proxy:
    build: ./proxy
    ports:
      - 8080:8080
    depends_on:
      - api
