version: '3'
services:
  api:
    platform: linux/amd64
    build: 
      context: ./api
      target: dev
    volumes:
      - ./api:/api
      # If you add an volume here make sure you add it to /bin/download-infini-gram-array.sh too
      - ./infinigram-array/v4_pileval_llama:/mnt/infinigram-array/v4_pileval_llama
      - ./infinigram-array/dolma_1_6_sample:/mnt/infinigram-array/dolma_1_6_sample
      - ./infinigram-array/dolma_1_7:/mnt/infinigram-array/dolma_1_7
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
  proxy:
    build: ./proxy
    ports:
      - 8080:8080
    depends_on:
      - api
