version: '3'
services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: uv.Dockerfile
      target: dev
    volumes:
      - ./api:/api
      # If you add an volume here make sure you add it to /bin/download-infini-gram-array.sh too
      - ./infinigram-array/v4_pileval_llama:/mnt/infinigram-array/v4_pileval_llama
      - ./infinigram-array/olmoe-mix-0924-dclm:/mnt/infinigram-array/olmoe-mix-0924-dclm
      - ./infinigram-array/olmoe-mix-0924-nodclm:/mnt/infinigram-array/olmoe-mix-0924-nodclm
      - ./infinigram-array/v4-olmoe-0125-1b-7b-anneal-adapt:/mnt/infinigram-array/v4-olmoe-0125-1b-7b-anneal-adapt
      - ./infinigram-array/v4-olmo-2-1124-13b-anneal-adapt:/mnt/infinigram-array/v4-olmo-2-1124-13b-anneal-adapt
      - ./infinigram-array/v4-olmo-2-0325-32b-anneal-adapt:/mnt/infinigram-array/v4-olmo-2-0325-32b-anneal-adapt
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - INDEX_BASE_PATH=/mnt/infinigram-array
      - LOG_LEVEL=DEBUG
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
  proxy:
    build: ./proxy
    ports:
      - 8080:8080
    depends_on:
      - api
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.115.1
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - logs:/var/log:ro
    environment:
      - GOOGLE_CLOUD_PROJECT
      - GOOGLE_CLOUD_QUOTA_PROJECT
    ports:
      # Collector prometheus port. The metrics are checked in tests
      - 8888
volumes:
  logs: