apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinigram-api-prod-worker-olmo-2-0325-32b
  namespace: infinigram-api
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: infinigram-api-worker-olmo-2-0325-32b
      env: prod
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      name: infinigram-api-prod-worker-olmo-2-0325-32b
      namespace: infinigram-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: onlyOneOfPerNode
                operator: In
                values:
                - infinigram-api-prod
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: PYTHON_ENV
          value: prod
        - name: ATTRIBUTION_QUEUE_URL
          valueFrom:
            secretKeyRef:
              key: ATTRIBUTION_QUEUE_URL
              name: attribution-worker
        - name: OTEL_SERVICE_NAME
          value: infinigram-api-worker
        - name: ASSIGNED_INDEX
          value: olmo-2-0325-32b
        image: WORKER_IMAGE:TAG
        imagePullPolicy: IfNotPresent
        name: infinigram-api-prod-worker-olmo-2-0325-32b
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: '32'
            memory: 128G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/infinigram-array/olmoe-mix-0924-dclm
          name: infinigram-array-olmoe-mix-0924-dclm
          readOnly: true
        - mountPath: /mnt/infinigram-array/olmoe-mix-0924-nodclm
          name: infinigram-array-olmoe-mix-0924-nodclm
          readOnly: true
        - mountPath: /mnt/infinigram-array/v4-olmo-2-0325-32b-anneal-adapt
          name: infinigram-array-v4-olmo-2-0325-32b-anneal-adapt
          readOnly: true
        - mountPath: /var/secrets
          name: worker-secrets
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-nodepool: cpu64-256g
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: infinigram-array-olmoe-mix-0924-dclm
        persistentVolumeClaim:
          claimName: infinigram-olmoe-mix-0924
          readOnly: true
      - name: infinigram-array-olmoe-mix-0924-nodclm
        persistentVolumeClaim:
          claimName: infinigram-olmoe-mix-0924-nodclm
          readOnly: true
      - name: infinigram-array-v4-olmo-2-0325-32b-anneal-adapt
        persistentVolumeClaim:
          claimName: infinigram-v4-olmo-2-0325-32b-anneal-adapt
          readOnly: true
      - name: worker-secrets
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: worker-secret-provider