apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- infinigram-storage-class.yaml
- volume-claims/dolma2-0625-base-shared.yaml
- volume-claims/olmoe-mix-0924-dclm.yaml
- volume-claims/olmoe-mix-0924-nodclm.yaml
- volume-claims/v4-olmo-2-0325-32b-anneal-adapt.yaml
- volume-claims/v6-dolma2-0625-v02-32b.yaml
- workers/infini-gram-worker-olmo-2-32b.yaml
- workers/infini-gram-worker-olmo-3-32b-instruct.yaml
