name: Lint and type-check PR

concurrency:
    group: unit-${{ github.ref }}
    cancel-in-progress: true

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
       python-version: '3.12' 
       cache: 'pip' 
    - run: pip install -r ./api/requirements/ci-requirements.txt
    - run: ruff check ./api

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
          cache: 'pip' 
      - run: pip install -r ./api/requirements/ci-requirements.txt
      - run: mypy --config ./api/pyproject.toml
